spring:
  profiles:
    active: dev
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5433/store_db
    password: leroy001
    username: postgres
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  thymeleaf:
    check-template-location: false


jwt:
  secret: ${JWT_TOKEN_SECRET}
  token-expiration: ${JWT_TOKEN_EXPIRATION:300}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true